/*
 * Copyright (c) 2026 Jaydeep Sahu
 * Practice / learning project
 */

package com.jaydeep.quizyai.service.impl;

import com.jaydeep.quizyai.constants.Prompts;
import com.jaydeep.quizyai.model.Option;
import com.jaydeep.quizyai.model.Question;
import com.jaydeep.quizyai.model.QuizResponse;
import com.jaydeep.quizyai.service.QuizService;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Collections;

@Service
public class QuizServiceImpl implements QuizService {
    private final static Logger logger = LogManager.getLogger(QuizServiceImpl.class);

    private final ChatClient quizClient;

    public QuizServiceImpl(ChatClient.Builder builder) {
        this.quizClient = builder.build();
    }


    /**
     * Generates a personalized greeting message using the AI model.
     *
     * @param name the name of the user
     * @return a greeting string generated by the AI
     */
    @Override
    public String sayHello(String name) {
        return quizClient.prompt()
                .user(u -> u.text(Prompts.WELCOME_PROMPT)
                        .param("name", name)
                        .param("time", LocalTime.now(ZoneId.of("Asia/Kolkata")).toString())
                )
                .call()
                .content();
    }

    /**
     * Generates a quiz by interacting with the AI model.
     * The response is automatically mapped to the QuizResponse POJO.
     *
     * @param category   the topic of the quiz
     * @param difficulty the difficulty level
     * @return a QuizResponse object containing randomized questions and options
     */
    @Override
    public QuizResponse generateQuiz(String category, String difficulty) {
        QuizResponse response = quizClient.prompt()
                .user(u -> u.text(String.format(Prompts.QUIZ_PROMPT, category, difficulty))
                )
                .call()
                .entity(QuizResponse.class);

        assert response != null;

        randomizeQuestionsAndAnswers(response);

        return response;
    }


    /**
     * Randomizes the order of questions and their options to ensure variety.
     * Updates the answer index and option keys accordingly.
     *
     * @param response the QuizResponse containing questions to be randomized
     */
    private void randomizeQuestionsAndAnswers(QuizResponse response) {
        logger.debug("Before shuffling: {}", response);

        Collections.shuffle(response.getQuestions());

        for (Question question : response.getQuestions()) {
            Collections.shuffle(question.getOptions());

            for (int i = 0; i < question.getOptions().size(); i++) {
                Option option = question.getOptions().get(i);
                option.setKey(i + 1);

                if (option.getValue().equals(question.getAnswer())) {
                    question.setAnswer(String.valueOf(option.getKey()));
                }
            }
        }

        logger.debug("After shuffling: {}", response);

    }


}
