/*
 * Copyright (c) 2026 Jaydeep Sahu
 * Practice / learning project
 */

package com.jaydeep.quizyai.controller;

import com.jaydeep.quizyai.model.*;
import com.jaydeep.quizyai.service.QuizService;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.ai.retry.NonTransientAiException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
public class QuizRestController {
    private final static Logger logger = LogManager.getLogger(QuizRestController.class);

    private final QuizService quizService;

    public QuizRestController(QuizService quizService) {
        this.quizService = quizService;
    }


    /**
     * Greets the user with a personalized message generated by the AI.
     *
     * @param name the name of the user to greet
     * @return a ResponseEntity containing the AI-generated greeting string
     */
    @GetMapping("/hello")
    public ResponseEntity<String> sayHello(@RequestParam(value = "name") String name) {

        try {
            String response = quizService.sayHello(name);
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body("Something went wrong");
        }
    }

    /**
     * Generates quiz questions based on the specified category and difficulty level.
     *
     * @param category   the topic of the quiz questions
     * @param difficulty the difficulty level (e.g., easy, medium, hard)
     * @return a ResponseEntity containing the AI-generated quiz questions in JSON format
     */
    @GetMapping("/quiz")
    public ResponseEntity<Response> generateQuiz(@RequestParam(value = "category") String category,
                                                 @RequestParam(value = "difficulty", defaultValue = "easy") String difficulty) {
        try {
            QuizResponse response = quizService.generateQuiz(category, difficulty);
//            QuizResponse response = getDummyQuizResponse();
            return ResponseEntity.ok(response);
        } catch (NonTransientAiException e) {
            logger.error("Failed to generate quiz questions due to rate limiting.");
            return ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS).body(new ErrorResponse("Failed to generate quiz questions due to rate limiting. Please try again later."));
        } catch (Exception e) {
            logger.error("Some error occurred while generating quiz questions. {}", e.getMessage());
            return ResponseEntity.internalServerError().body(new ErrorResponse("Failed to generate quiz questions. Please try again later."));
        }
    }

    /**
     * For Testing Purpose
     *
     */
    private QuizResponse getDummyQuizResponse() {
        QuizResponse quizResponse = new QuizResponse();

        List<Question> questionList = new ArrayList<>();

        Question question = new Question();
        question.setQuestion("Who played the role of DC superhero 'The Flash' in CW TV Series?");
        question.setOptions(
                List.of(new Option(1, "Robert Downey Jr."),
                        new Option(2, "Ezra Miller"),
                        new Option(3, "John Crasinskey"),
                        new Option(4, "Grant Gustin")
                )
        );
        question.setAnswer("4");

        question.setId(1);
        questionList.add(question);

        question.setId(2);
        questionList.add(question);

        question.setId(3);
        questionList.add(question);

        question.setId(4);
        questionList.add(question);

        question.setId(5);
        questionList.add(question);

        quizResponse.setQuestions(questionList);

        return quizResponse;
    }


}
