/*
 * Copyright (c) 2026 Jaydeep Sahu
 * Practice / learning project
 */

package com.jaydeep.quizyai.controller;

import com.jaydeep.quizyai.constants.Prompts;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalTime;
import java.time.ZoneId;

@RestController
public class QuizRestController {

    private final ChatClient quizClient;

    public QuizRestController(ChatClient.Builder quizClientBuilder) {
        this.quizClient = quizClientBuilder.build();
    }

    /**
     * Greets the user with a personalized message generated by the AI.
     *
     * @param name the name of the user to greet
     * @return a ResponseEntity containing the AI-generated greeting string
     */
    @GetMapping({"/", "hello"})
    public ResponseEntity<String> sayHello(@RequestParam(value = "name") String name) {

        try {
            String response = quizClient.prompt()
//                    .system(Instructions.WELCOME_BOT_BEHAVIOUR)
                    .user(u -> u.text(Prompts.WELCOME_PROMPT)
                            .param("name", name)
                            .param("time", LocalTime.now(ZoneId.of("Asia/Kolkata")).toString())
                    )
                    .call()
                    .content();
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body("Something went wrong");
        }
    }

}
