# Copyright (c) 2026 Jaydeep Sahu

spring.application.name=quizyai
server.port=8080

## AI Config
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${SECRET_API_KEY}
#spring.ai.openai.chat.options.model=google/gemma-3-12b-it:free
spring.ai.openai.chat.options.model=meta-llama/llama-3.3-70b-instruct:free
spring.ai.openai.chat.completions-path=/chat/completions


## Logging Config
logging.level.com.jaydeep.quizyai=DEBUG
logging.level.org.springframework.ai=WARN
logging.level.org.springframework.ai.retry=OFF
logging.level.org.springframework.ai.retry.autoconfigure=OFF